### PR TITLE
Add Chinese in Kernel website

### PR DESCRIPTION
**Pull request by notthere-2023**
## Summary of changes
_Description of the changes included in this pull request. 

This change means to add Chinese translation for Kernel. I came across Kernel not long, but feel belonging by its values, so I try to see what I can do to learn more about Kernel and contribute to it.
I couldn't join the Slack Group before according to the website guidance, so I tried to start it here.

Steps to follow to confirm the feature is completed or the bug/issue is resolved. 
Are there any dependencies? 
No
Does this code break any existing functionality or introduce any risk?_
No it doesn't

## Relevant Context

- Feature: [ticket number](link to project management ticket)
- Relevant Pull Request: # 

## How Has This Been Tested?
I haven't test it, but would like to know how to test. Besides this, there no other areas of code being affected as far as I concerned.

## Further comments

--- 
## Types of changes

- [x] Content edit, File upload, content addition
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by andytudhope** [comment]
This is very kind, thank you. I will see if I can find someone to help us review. Have you tried applying to Block 8, which begins next year?

https://apply.kernel.community

**Comment by notthere-2023** [comment]
Yeah I have applied for it! Thank you for your reply, and I will translate
it at my pace first.

Andy Tudhope ***@***.***> 于2023年12月21日周四 04:12写道：

**Comment by andytudhope** [comment]
I'm going to merge here, and you can continue translating pages to Chinese as and when you see fit :pray:

**Comment by notthere-2023** [comment]
Ok and sorry for the delayed reply, I want to continue this.

Andy Tudhope ***@***.***> 于2024年1月19日周五 16:48写道：

**Pull request merged**
