### PR TITLE
Fix menu/close icon colour on mobile light screen

### LINKED ISSUE #68: No Menu Icon on Mobile Light Screen
**Describe the bug**

When light/white screen is selected on mobile view, no menu item appears.

**To Reproduce**
1. Go to https://kernel.community/en
2. Use any mobile phone
3. See the lack of a menu item.

**Expected behavior**
A black hamburger menu should appear. See the dark screen for the expected behaviour.

**Screenshots**

Screenshot from 2021-06-08 17-33-16

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android 10
 - Browser: Brave

### PR DESCRIPTION
**Pull request by sharonsheah**
### Attention (CC)

@andytudhope 

## Summary of changes

_Description of the changes included in this pull request. 
Steps to follow to confirm the feature is completed or the bug/issue is resolved. 
Are there any dependencies? 
Does this code break any existing functionality or introduce any risk?_

- Added `colorMode` to `Header` const
- Added icon color logic based on `colorMode`

How to test:
1. Go to https://kernel.community/en
2. Use any mobile phone
3. Change to light mode if needed
4. Observe burger menu is visible  
5. Click on burger menu
6. Observe close icon is visible

## Relevant Context

- Issue: Closes #68 

## How Has This Been Tested?

Tested manually/visually:
- Checked that the error is there before adding changes to code
- Add changes to code
- Visually tested locally and observed expected behaviour of icon colour depending on colourMode

## Screenshots (if appropriate):

image
image

## Further comments

--- 
## Types of changes

- [ ] Content edit, File upload, content addition
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by andytudhope — APPROVED** [review]
Perfect, thank you :pray:

**Comment by andytudhope** [comment]
@sharonsheah if you were to leave an ETH address here that you control (not an exchange account) something might appear in it magically :wink: 

Your PR is being deployed to prod as we speak. Thank you again.

**Comment by sharonsheah** [comment]
😱

0xa07b4d615FDa051F68D507DFfAF0BaAf986453D9

Thank you so much!

**Comment by andytudhope** [comment]
https://etherscan.io/tx/0x126fb05402a06d4cb7c150d2573af50d95ae11be63f2f4cac75d4b66b046e03c

You should be able to view it on OpenSea :wink:

**Pull request merged**
